version: "2"
services:
  consul:
    image: consul:0.7.3
    ports:
      - "8300:8300"
      - "8301"
      - "8302"
      - "8500:8500"
      - "53:8600"
    volumes:
      - consul-data:/consul/data
      - consul-data:/consul/config
    networks: [spring-network]
  vault:
    image: vault:0.6.4
    environment:
      #VAULT_REDIRECT_INTERFACE: ...
      #VAULT_CLUSTER_INTERFACE: ...
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_LOCAL_CONFIG: '{"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
    ports: ["8200:8200"]
#    depends_on: ["consul"]
    links: ["consul:consul"]
    volumes: ["vault-data:/vault/file"]
    networks: [spring-network]
volumes:
  consul-data: {}
  vault-data: {}
networks:
  spring-network:
    driver: bridge
