version: "2.1"
volumes:
  vault-data:
networks:
  backing-services:
services:
  vault:
    image: vault:0.8.1
    environment:
      #VAULT_REDIRECT_INTERFACE: ...
      #VAULT_CLUSTER_INTERFACE: ...
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_LOCAL_CONFIG: '{"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
    ports: ["8200:8200"]
    volumes: ["vault-data:/vault/file"]
    networks: [backing-services]
