version: "2.1"
services:
  mysql:
    image: mysql:5.7.19
    #image: healthcheck/mysql
    environment:
      #MYSQL_ONETIME_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: vault
      MYSQL_USER: vault
      MYSQL_PASSWORD: vault
    ports: ["3306:3306"]
    volumes: ["mysql-data:/var/lib/mysql"]
    networks: [backing-services]
  consul:
    image: consul:0.9.2
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_HTTP_ADDR: 0.0.0.0
      CONSUL_ALLOW_PRIVILEGED_PORTS:
      CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true, "skip_leave_on_interrupt": true, "disable_update_check": true}'
      # curl http://localhost:8500/v1/health/service/consul?pretty
    ports:
      - "8500:8500"
      - "8600:53/udp"
    volumes:
      - consul-data:/consul/data
      - consul-data:/consul/config
    networks: [backing-services]
  vault:
    cap_add:
      - IPC_LOCK
    image: vault:0.8.1
    depends_on:
      - mysql
      - consul
    environment:
      #VAULT_REDIRECT_INTERFACE: ...
      #VAULT_CLUSTER_INTERFACE: ...
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_LOCAL_CONFIG: '{"backend":{"consul":{"address":"consul:8500","advertise_addr":"http://0.0.0.0","path":"demo_vault"}},"disable_mlock":true,"default_lease_ttl":"168h","max_lease_ttl":"720h"}'
    ports: ["8200:8200"]
    volumes: ["vault-data:/vault/file"]
    networks: [backing-services]
volumes:
  mysql-data: {}
  consul-data: {}
  vault-data: {}
networks:
  backing-services:
    driver: bridge
