version: "2.1"
services:
  mysql:
    image: mysql:5.7.19
    #image: healthcheck/mysql
    environment:
      #MYSQL_ONETIME_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: vault
      MYSQL_USER: vault
      MYSQL_PASSWORD: vault
    ports: ["3306:3306"]
    volumes: ["mysql-data:/var/lib/mysql"]
    #networks: [backing-services]
  vault:
    image: vault:0.8.1
    depends_on: [mysql]
    environment:
      #VAULT_REDIRECT_INTERFACE: ...
      #VAULT_CLUSTER_INTERFACE: ...
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_LOCAL_CONFIG: '{"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
    ports: ["8200:8200"]
    volumes: ["vault-data:/vault/file"]
    #networks: [backing-services]
volumes:
  mysql-data: {}
  vault-data: {}
#networks:
#  backing-services:
#    driver: bridge
